### ISSUE TITLE
Version du module et infos via js

### ISSUE THREAD

**Issue by sebfie** [Cocolis-1/cocolis-prestashop#23]
Il faudrait pouvoir me rajouter une variable en javascript sur window qui me retourne la version du module step

**Comment by btnalexandre** [comment]
Qu'est-ce que t'entends par window ?

**Comment by sebfie** [comment]
Tu sais la variable globale javascript en console, window.cocolis_module_infos par exemple

**Comment by btnalexandre** [comment]
Ah d'accord, je vais faire ça

**Comment by btnalexandre** [comment]
https://github.com/Cocolis-1/cocolis-prestashop/commit/1ece0b598a702844f06cac112ea24f9718571c0c
