### ISSUE TITLE
[BUG] Affichage du mode de livraison Cocolis si can_match négatif

### ISSUE THREAD

**Issue by AntoineCocolis** [Cocolis-1/cocolis-prestashop#24]
Dans le cas où le can_match est négatif, le mode de livraison Cocolis est affiché avec un prix à 0€. Il ne faut pas qu'il soit affiché. Pour tester sur staging, il faut mettre un code postal de livraison de 15000 ou 13150 qui renvoie result: false

<img width="1433" alt="Capture d’écran 2021-11-30 à 18 11 43" src="https://user-images.githubusercontent.com/59686802/144094649-cfa5d228-94a6-4be0-aaa6-9bbc59686bf2.png">

Ce que l'on veut : si result: false, on ne propose pas cocolis

**Comment by btnalexandre** [comment]
https://github.com/Cocolis-1/cocolis-prestashop/releases/tag/1.0.8

**Comment by btnalexandre** [comment]
Possible de tester @AntoineCocolis stp avec assurance et sans assurance

**Comment by btnalexandre** [comment]
On peut clôturer @AntoineCocolis ?

**Comment by AntoineCocolis** [comment]
je ne sais pas

@sebfie tu as eu des retours de si c'était OK chez la personne qui nous a remonté le problème ?

**Comment by sebfie** [comment]
Yes c'est ok
