### ISSUE TITLE
[Doc] Workflow commande

### ISSUE THREAD

**Issue by sebfie** [Cocolis-1/cocolis-prestashop#25]
Il faut faire un schéma pour expliquer les étapes d'une commande e-commerce sur prestashop : 

• Un client commande sur votre site
• La commande est payée
• Une livraison est créée sur cocolis.fr si le mode de livraison de la commandé était cocolis. Les étapes sont les suivantes : https://res.cloudinary.com/cocolis-prod/image/upload/v1606130493/Documentation/Flux_financiers_Disruptual_x_Cocolis_1_qmmib1.svg
• La commande vit sa vie sur cocolis.fr et votre site est notifié de l’avancée via les webhooks qui semblent bien configurés (j’ai vérifié)
• La commande est livrée sur cocolis, elle va être marquée comme livrée chez vous

Tu peux me faire ca et le rajouter dans la doc ?

**Comment by btnalexandre** [comment]
![workflow](https://user-images.githubusercontent.com/13454856/149142557-65fa791c-9375-47f6-9e57-8661418ce9f9.png)

J'ai fait ça avec le logiciel Diagrams dans Setapp, j'ai fait au plus simple ?

**Comment by sebfie** [comment]
Moi ca me semble pas mal, @JulietteCortes ?

**Comment by sebfie** [comment]
En fait ca change le status de la commande, ca la passe en terminée, c'est ce qu'à voulu modéliser Alexandre je pense.

**Comment by JulietteCortes** [comment]
yes, mais du coup je pense que ce n'est pas vers cet endroit que cela doit renvoyer.

**Comment by btnalexandre** [comment]
> En fait ca change le status de la commande, ca la passe en terminée, c'est ce qu'à voulu modéliser Alexandre je pense.

Yes c'est bien ce que je voulais modéliser mais du coup je redirige vers quoi @JulietteCortes ?

**Comment by JulietteCortes** [comment]
Tois options : 
- soit ça vous va à tous les deux, la démocratie l'emporte on laisse comme ça
- soit on redirige vers "Votre site"
- soit on enlève

**Comment by btnalexandre** [comment]
@sebfie je te laisse voter en premier :)

**Comment by sebfie** [comment]
@btnalexandre Ecris sur le graphe les status Prestashop

**Comment by btnalexandre** [comment]
J'ai pas compris où je dois écrire les status @sebfie

**Comment by sebfie** [comment]
![CleanShot 2022-01-29 at 12 21 27](https://user-images.githubusercontent.com/862129/151659013-2d7ef892-48f2-41ec-b7b8-3378ba5966b3.png)

Un peu sous chaque bloc

**Comment by btnalexandre** [comment]
![workflow](https://user-images.githubusercontent.com/13454856/153269992-c1a300ef-0b2a-4c18-88bf-5a57803f70a7.png)

Est-ce que c'est mieux ?

**Comment by sebfie** [comment]
Moi ca me va mieux, @JulietteCortes  ?

**Comment by JulietteCortes** [comment]
Moi aussi, très bien!

**Comment by btnalexandre** [comment]
Okay j'ajoute à la doc ?

**Comment by sebfie** [comment]
Vas y

**Comment by btnalexandre** [comment]
@sebfie je te laisse merge si c'est good pour toi

**Comment by btnalexandre** [comment]
Je clos, ticket terminé

**Comment by btnalexandre** [comment]
En fait je réouvre, je vois pas la modif dans la doc ici @sebfie :(

https://doc.cocolis.fr/docs/cocolis-prestashop/ZG9jOjQ2NDA2-introduction

**Comment by sebfie** [comment]
Normal, faut faire une release :p

**Comment by sebfie** [comment]
C'est choses faite
